name: Build and Bundle Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    # if: false  # This workflow is disabled
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Checkout raylib
      uses: actions/checkout@v3
      with:
        repository: raysan5/raylib
        path: libs/raylib

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev
    
    - name: Build raylib
      run: |
        cd libs/raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        cp libraylib.a ../libraylib.a
        mkdir -p ../include/
        cp raylib.h ../include/
        cp raymath.h ../include/
        cp rlgl.h ../include/
        cd ../../..

    - name: Build Project
      run: |
        make
            
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "vertical-artifacts-linux"
        path: build/
