name: Build MacOS arm64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_macos_arm64:
    # if: false  # This workflow is disabled
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Checkout raylib
      uses: actions/checkout@v2
      with:
        repository: raysan5/raylib
        path: libs/raylib
    
    - name: Build raylib
      run: |
        cd libs/raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        cp libraylib.a ../libraylib.a
        mkdir -p ../include/
        cp raylib.h ../include/
        cp raymath.h ../include/
        cp rlgl.h ../include/
        cd ../../..

    - name: Build Project
      run: |
        make
            
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "vertical-artifacts-arm64"
        path: build/
